apiVersion: v1
kind: Pod
metadata:
  name: podtest2
  labels:
    app: nginx
spec:
  containers:
      - name: cont
        image: nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: podtest3
  labels:
    app: nginx
spec:
  containers:
    - name: cont
      image: nginx:alpine