version: '3'
services:
  drupal:
    volumes:
      - drupal-html:/var/html/www/html
    image: drupal:8-apache
    ports:
    - "80:80"
    networks:
      - net
  postgres:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: drupal
    volumes:
      - "./data:/var/lib/postgresql/data"
    networks:
      - net
volumes:
  drupal-html:
networks:
  net: